### PR TITLE
Add note on using =? for exploring config

### PR DESCRIPTION
**Pull request by SchumBlubBlub**
https://github.com/radare/radare2/issues/6657#issuecomment-277255616

### CODE REVIEW

**Comment by Maijin** [comment]
You can also use `et` for getting type.

**Comment by SchumBlubBlub** [comment]
Yeah, but that's clear from the current value, and easy to find in the ?help. I haven't seen =? mentioned anywhere, and it's obviously not part of the `=` help. I guess @radare just loves APL.

**Comment by Maijin** [comment]
Feel free to fix the e? to add it 👍

**Comment by SchumBlubBlub** [comment]
Glad to, but all the other commands ?help is consistent about prefix, you sure?
Also, can you look at output of `?*`, it seems like some error messages result.

**Comment by SchumBlubBlub** [comment]
@Maijin, please revert. It's not general, just works for `scr.nkey`. It is good idea, maybe I add later.

**Comment by Maijin** [comment]
it's useful for arch, bin etc. so i'm leaving it.

**Comment by SchumBlubBlub** [comment]
ok, can you plz change it to "Some commands support..." at least?

**Pull request merged**
