### PR TITLE
Fix load_bytes() signature on plugins/dev-bin.md

### PR DESCRIPTION
**Pull request by davidpolverari**
Fix needed because of https://github.com/radare/radare2/pull/11679 in r2.

### CODE REVIEW

**Comment by XVilka** [comment]
Also fix required in r2lang plugins

**Comment by davidpolverari** [comment]
Where? I don't know r2lang enough.

**Comment by XVilka** [comment]
@davidpolverari here https://github.com/radare/radare2-bindings/tree/master/libr/lang

**Comment by davidpolverari** [comment]
Looks like it had already been done at https://github.com/radare/radare2-bindings/commit/eb2c920704dfde8ed04db3959983308613757b47#diff-e4a0d20b054a112c72aae36e9b8c0e98R318, no? At least the return type has been changed, but I don't see the void **bin_obj parameter there.

**Comment by radare** [comment]
Load bytes will be removed soon. No need to spend time documenting it

**Comment by davidpolverari** [comment]
Ok! Thanks!

**Pull request closed without merging**
