### PR TITLE
Update introduction/basic_usage.md

### PR DESCRIPTION
**Pull request by benquike**
Add the introduction of VA/non-VA addressing mode

### CODE REVIEW

**Comment by Maijin** [comment]
See @radare comment https://github.com/radare/radare2book/pull/24#issuecomment-203697055 also, why closing and opening PR oO each time ??

**Comment by benquike** [comment]
Sorry, I just don't want to have too many commits in your repo.

**Comment by benquike** [comment]
@Maijin I modified the commit according to @radare 's comments this time. If you are not satisfied with this commit, could you please tell me how to modify it.

**Comment by Maijin** [comment]
Thanks ;)

**Pull request merged**
