### PR TITLE
Update command output and rename commands that have changed.

### PR DESCRIPTION
**Pull request by MaskRay**

### CODE REVIEW

**Comment by Maijin** [comment]
Hello ?

**Comment by MaskRay** [comment]
@Maijin Hello!

**Comment by Maijin** [comment]
Can you do the change so I can merge ?

**Comment by MaskRay** [comment]
@Maijin  What change?

**Comment by Maijin** [comment]
image

I said what to do in the review, You removed "the rest of the string is passed to currently loaded IO plugin (a debugger, for example). If no plugin can handle the command, posix_system() is called to pass the command to your shell. To make sure your command is directly passed to the shell, prefix it with two exclamation signs `!!`."

**Comment by MaskRay** [comment]
I cannot see your review in my view of Github. Reverted this change.

**Comment by Maijin** [comment]
Yes probably that was the reason, thanks pointing it out ;)

**Pull request merged**
